CLI Grep
nikolay-egorov/CLI pull request #2
Opened 2021-03-02 18:05 UTC by nikolay-egorov

2021-03-18 00:09 UTC, aleksZubakov requested changes
- старайтесь, пожалуйста, делать pr так, чтобы в нем были изменения, касающиеся только текущего задания
- репозиторий не приватный, хотя должен быть 

- не работает с пайпом (видимо, ждет пользовательский ввод): `cat build.gradle.kts | grep plugin`
- `-w` тоже не работает: `grep -w plugins build.gradle.kts` должен вывести `plugins {`, но ничего не выводит 
- падаем, если пользователь передал невалидное значение: `grep -A aaa plugin build.gradle.kts`

2021-03-20 10:05 UTC, nikolay-egorov commented
Поправил баги. Баг с пайпом при повторном использовании перестает быть, если объединить эту ветку и `test-base-dev`

2021-03-24 02:19 UTC, aleksZubakov commented
Так продвиньте ветку, если это фиксит проблему

2021-03-24 02:21 UTC, aleksZubakov commented
Вообще по-хорошему должна была быть ровно одна проверка, т.к. прислали после мягкого, но ок уже

2021-03-24 02:21 UTC, closed without merging