Ls and cd
nikolay-egorov/CLI pull request #3
Opened 2021-03-21 14:38 UTC by katusha97

2021-03-30 01:39 UTC, aleksZubakov requested changes
Делайте pr так, чтобы в нем были только файлы, относящиеся к заданию, пожалуйста.

А где ревью на архитектуру? По коду более-менее ок, 7 баллов

2021-03-30 01:39 UTC, aleksZubakov commented on src/test/kotlin/nikolay/egorov/cli/commands/CommandCreatorTest.kt
> +//        assertTrue(created is ExternalCommand)
Не нужно ломать чужие тесты своим кодом, стоило их поправить на что-то похожее, они же не просто так написаны

2021-03-30 01:39 UTC, aleksZubakov commented on src/main/kotlin/nikolay/egorov/cli/runtime/Environment.kt
> +        set(value) {myCurrentDirectory = value}
Бесполезное свойство, можно просто было `myCurrentDirectory` сделать публичной

`Path` итак не nullable, аннотация не нужна.

2021-04-03 10:53 UTC, katusha97 commented
Ревью на архитектуру сделала прямо  в пул реквест с решением Коли (CLI First task). https://github.com/nikolay-egorov/CLI/pull/1

2021-04-15 13:58 UTC, aleksZubakov commented
Это комментарии к конкретным кускам кода, а не ревью архитектуры

Ну и я оставлял 23 дня назад комментарий: 

> Сделайте общие комментарии про архитектуру в своем форке, пожалуйста, не здесь :)

Окончательные 7 баллов

2021-04-15 13:58 UTC, closed without merging